seed: 123
grid:
  lambdas: {start: 450, stop: 700, step: 1}
channels:
  - {name: C1, center_nm: 500, bandwidth_nm: 30}
  - {name: C2, center_nm: 550, bandwidth_nm: 30}
  - {name: C3, center_nm: 600, bandwidth_nm: 30}
  - {name: C4, center_nm: 650, bandwidth_nm: 30}
fluors:
  - {name: F1, model: gaussian, params: {mu: 520, sigma: 12}, brightness: 1.0}
  - {name: F2, model: skewnorm, params: {mu: 560, sigma: 10, alpha: 6}, brightness: 0.8}
  - {name: F3, model: lognormal, params: {mu: 6.2, sigma: 0.08}, brightness: 0.7}
spatial:
  field: {H: 128, W: 128, pixel_size_nm: 100}
  abundances:
    kind: dots
    density_per_100x100_um2: 50
    spot_profile: {kind: gaussian, sigma_px: 1.2}
forward:
  use_S: false
  use_PSF: false
  photon_counting: true
  noise: {gain: 1.0, read_sigma: 1.0, dark_rate: 0.0}
known:
  M: true
unmix:
  - {method: nnls}
  - {method: lasso, alpha: 0.01}
  - {method: nmf, K: 3, n_iter: 200}
  - {method: em_poisson, n_iter: 150}
outputs:
  save: {npz: true}

