seed: 123
grid:
  lambdas: {start: 450, stop: 700, step: 1}
channels:
  - {name: C1, center_nm: 520, bandwidth_nm: 30}
  - {name: C2, center_nm: 560, bandwidth_nm: 30}
  - {name: C3, center_nm: 610, bandwidth_nm: 30}
fluors:
  - {name: F1, model: gaussian, params: {mu: 505, sigma: 10}, brightness: 1.0}
  - {name: F2, model: skewnorm, params: {mu: 540, sigma: 12, alpha: 4}, brightness: 0.9}
  - {name: F3, model: lognormal, params: {mu: 6.1, sigma: 0.07}, brightness: 0.8}
  - {name: F4, model: mixture, params: {mus: [600, 630], sigmas: [8, 10], weights: [0.6, 0.4]}, brightness: 1.1}
  - {name: F5, model: gaussian, params: {mu: 650, sigma: 9}, brightness: 1.0}
spatial:
  field: {H: 128, W: 128, pixel_size_nm: 100}
  abundances:
    kind: dots
    density_per_100x100_um2: 60
    spot_profile: {kind: gaussian, sigma_px: 1.2}
forward:
  use_S: false
  use_PSF: false
  photon_counting: true
  noise: {gain: 1.0, read_sigma: 1.5, dark_rate: 0.0}
known:
  M: true
priors:
  A: {nonneg: true, sparsity: 0.9}
unmix:
  - {method: lasso, alpha: 0.02}
  - {method: nmf, K: 5, n_iter: 300}
outputs:
  save: {npz: true}

